### PR TITLE
Fix ci actions

### PR DESCRIPTION
**Pull request by LanderU**

### CODE REVIEW

**Comment by vmayoral** [comment]
Thanks for this @LanderU, with this, shall I submit the CI PR to ros-planning/moveit2 master? I will be asking for your help to review it

**Comment by LanderU** [comment]
@vmayoral, this is HRIM repo.

**Comment by vmayoral** [comment]
My bad, you're right. Nevertheless, it still applies, I'll be asking for your help if that's ok.

**Comment by LanderU** [comment]
> I'll be asking for your help if that's ok.

Sure!

**Comment by vmayoral** [comment]
https://github.com/AcutronicRobotics/moveit2/issues/27

thanks!

**Pull request merged**
