### PR TITLE
Added testWorkspace function:

### PR DESCRIPTION
**Pull request by LanderU**
* Check the compiled ws

Signed-off-by: Lander Usategui <lander.usategui@gmail.com>

### CODE REVIEW

**Comment by ahcorde** [comment]
Thanks for the commit @LanderU :+1: 

```
--merge-install --packages-select hrim_qa
```

**Comment by ahcorde** [comment]
tests are failing, can we show the output of the tests?

**Comment by LanderU** [comment]
Looking into it locally!

**Comment by LanderU** [comment]
The logic of checking the tests is wrong. I'm fixing it.

**Comment by LanderU** [comment]
Ready!!!

**Pull request merged**
