### PR TITLE
Installator

### PR DESCRIPTION
**Pull request by LanderU**
closes https://github.com/erlerobot/HRIM/issues/47

### CODE REVIEW

**Comment by LanderU** [comment]
I'll fix the conflicts.

**Comment by abilbaotm** [comment]
Please do not merge this until https://github.com/erlerobot/HRIM/issues/47

**Comment by LanderU** [comment]
Ready to be uploaded!

**Comment by LanderU** [comment]
In order to merge this PR we need to have some extra features that @ibaiape is working on.

**Comment by abilbaotm** [comment]
PR #48 is now merged to this (#46). Now this PR closes https://github.com/erlerobot/HRIM/issues/47

**Comment by ibaiape** [comment]
> In order to merge this PR we need to have some extra features that @ibaiape is working on.

Yeah this should wait for the restructure (no small feature actually).

Will get back to you ASAP.

**Comment by abilbaotm** [comment]
Changing to `cleanup` as it is the next RC

**Pull request merged**
